name: test_release_4
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - asn1crypto
  - blas
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - cryptography
  - elementpath
  - h5py
  - hdf5
  - hdmf=1.6.1
  - python=3.7.4
  - pytz
  - requests
  - scipy
  - setuptools
  - six
  - sqlite
  - urllib3
  - wheel
  - xmlschema
  - zlib
  - vdom
  - pyyaml
  - pytest



