{% set data = load_setup_py_data() %}


package:
  name: test_release_4
  version: {{ data.get('version') }}

source:
  - path: setup.py
  - path: ./dir_to_include
  - path: LICENSE

build:
  number: 0

requirements:
  build:
    - python=3.7.4
    - pip
    - setuptools

  run:
    - python=3.7.4
